resources:
- name: anniversaries-api
  type: git
  source:
    uri: https://github.com/bu3/anniversaries-api
    branch: master

- name: cloud-foundry
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organisation))
    space: ((cf-space))

jobs:
- name: unit-test
  plan:
  - get: anniversaries-api
    trigger: true
  - task: unit tests
    file: anniversaries-api/ci/tasks/unit-test.yml

- name: integration-tests
  plan:
  - get: anniversaries-api
    trigger: true
  - task: unit tests
    file: anniversaries-api/ci/tasks/integration-test.yml

- name: deploy
  plan:
  - get: anniversaries-api
    passed: [unit-test, integration-tests]
    trigger: true
  - task: unit tests
    file: anniversaries-api/ci/tasks/build.yml
  - put: cloud-foundry
    params:
      manifest: ./artifact/manifest.yml
      current_app_name: anniversaries-api
